---
title: "Scratch Leaflet v1"
author: "Philip Tanofsky"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Required packages
library(tidyverse)
library(ggplot2)
#library(skimr)
#library(tidyjson)
#library(geosphere)
library(lubridate)
# library(ggmap)
#library(forcats)
#library(scales)
library(jsonlite)
library(leaflet)
```

```{r}
#Station_Information.json
citibike_station_raw <- fromJSON("Station_Information.json")
citibike_station_info <- citibike_station_raw$data$stations

citibike_station_info <- citibike_station_info %>%
  select("station_type", "short_name", "has_kiosk", "region_id", "name", "lat", "station_id", "external_id", "capacity", "lon", "electric_bike_surcharge_waiver", "legacy_id")

(citibike_station_info)
```

```{r}
citibike_station_info %>%
  filter(region_id == 71)
```

```{r}
nyc_citibike_station_info <- citibike_station_info %>%
  filter(region_id == 71)
```

```{r}
# from: https://rstudio.github.io/leaflet/
m <- leaflet() %>%
  addTiles() %>% # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m # Print the map
```

leaflet() returns a Leaflet map widget, which stores a list of objects that can be modified or updated later.

```{r}
# set value for the minZoom and maxZoom settings
leaflet(options = leafletOptions(minZoom=0, maxZoom=18))
```

```{r}
# Using basemaps
m <- leaflet() %>% setView(lng = -71.0589, lat = 42.3601, zoom=12)
m %>% addTiles()
```

```{r}
m %>% addProviderTiles(providers$Stamen.Toner)
```

```{r}
m %>% addProviderTiles(providers$CartoDB.Positron)
```

```{r}
m %>% addProviderTiles(providers$Esri.NatGeoWorldMap)
```

```{r}
# Combining Tile Layers
m %>% addProviderTiles(providers$MtbMap) %>%
  addProviderTiles(providers$Stamen.TonerLines,
                   options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLabels)
```

```{r}
# Using basemaps for NYC
m <- leaflet() %>% setView(lng = -73.9, lat = 40.75, zoom=11)
m %>% addTiles()
```

```{r}
# Using basemaps for NYC
m <- leaflet(data=nyc_citibike_station_info) %>% 
#  setView(zoom=12) %>%
  addTiles() %>%
  addCircleMarkers(~lon, ~lat, popup=~as.character(name), label=~as.character(name), radius=.5)

# Display map
m
```

```{r}
# Shiny app link: https://shiny.rstudio.com/tutorial/written-tutorial/lesson2/
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


~~~~~

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
